[package]
name = "engine-config"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
thiserror.workspace = true
tracing.workspace = true
serde.workspace = true
toml = "0.8"
notify.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
engine-models = { path = "../engine-models" }
